**NUMPY**

* numpy -> Numeric Python
* listelerden 50 kata kadar daha hızlı 
* çok boyutlu arrayler mtrisler üzerinde yüksek perfonmanslı çalışma imkanı sağlar
* veri tipleri homoje yapıda olamlıdır. Tüm elemanlar aynı veri tipinde olmalıı
* numpy dizilerinin veri tipi ndarray dir
pip install numpy 

In [3]:
import numpy as np

In [1]:
import numpy as np
nd = np.array([1,2,3,4,5]) #liste
print(nd)


[1 2 3 4 5]


In [2]:
print(type(nd))

<class 'numpy.ndarray'>


In [5]:
nd = np.array((1,2,3,4,5,6,7,8)) #tuple
print(nd)

[1 2 3 4 5 6 7 8]


0 boyutlu diziler

In [6]:
nd = np.array(48)
print(nd)

48


1-D DİZİLER

In [8]:
nd = np.array([1,2,3,4,5,6,7,8])
print(nd)

[1 2 3 4 5 6 7 8]


2-D DİZİLER


In [9]:
nd_2d = np.array([[1,2,3,4,5,6,7,8],[1,2,3,4,5,6,7,8]])

print(nd_2d)

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


3-D DİZİLER


In [ ]:
nd_3d = np.array( )